const dotenv = require('dotenv').config();
const express = require('express');
const app = express();
const session = require('express-session');
const bodyParser = require('body-parser');
const flash = require('connect-flash');
var path = require('path');
var fileSystem = require('fs');
var geoip = require('geoip-country');
app.use(express.urlencoded({extended:false}));
app.use(bodyParser.urlencoded({extended:true}));
app.use(session({secret: 'gadminshhh', saveUninitialized: true, resave: true}));
app.use(flash());
app.use(function (req, res, next){
    res.locals.success_messages = req.flash('success_messages');
    res.locals.error_messages = req.flash('error_messages');
    res.locals.additional_charge = req.flash('additional_charge');
    next();
});
const port = process.env.PORT || 3005;
app.use(express.static('./public'));
app.set('view engine', 'ejs');
const main = require('./routes/main');
const category = require('./routes/category');
const product = require('./routes/product');
const order = require('./routes/order');
const store = require('./routes/store');
const awsupload = require('./routes/awsupload');
const influencer = require('./routes/influencer');
const supplier = require('./routes/supplier');
const country = require('./routes/country');
const support = require('./routes/support');
const specialp = require('./routes/specialp');
const trendingp = require('./routes/trendingp');
const veriantp = require('./routes/veriantp');
app.use('/main', main);
app.use('/category', category);
app.use('/product', product);
app.use('/order', order);
app.use('/store', store);
app.use('/awsupload',awsupload);
app.use('/influencer',influencer);
app.use('/supplier',supplier);
app.use('/country',country);
app.use('/support',support);
app.use('/specialp',specialp);
app.use('/trendingp',trendingp);
app.use('/veriantp',veriantp);
app.get('/', (req, res) => {
    res.render('pages/login', {'ociurl' : process.env.S3_IMAGE_URL});
});
app.listen(port, () => console.log(`Admin App:${port}`));